SCREEN_WIDTH = 160
SCREEN_HEIGHT = 120
STONE_INTERVAL = 10
NAME_SCENE = "name"
START_SCENE = "start"
PLAY_SCENE = "play"
LEADERBOARD_SCENE = "leaderboard"

STONE_SPEED = 0.7
PLAYER_SPEED = 2.5

PLAY_SCREEN_COLOR= "pyxel.COLOR_GREEN"